/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ReservationService } from "../reservation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReservationCreateInput } from "./ReservationCreateInput";
import { ReservationWhereInput } from "./ReservationWhereInput";
import { ReservationWhereUniqueInput } from "./ReservationWhereUniqueInput";
import { ReservationFindManyArgs } from "./ReservationFindManyArgs";
import { ReservationUpdateInput } from "./ReservationUpdateInput";
import { Reservation } from "./Reservation";
@swagger.ApiBasicAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReservationControllerBase {
  constructor(
    protected readonly service: ReservationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Reservation })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ReservationCreateInput
  ): Promise<Reservation> {
    return await this.service.create({
      data: {
        ...data,

        apartment: data.apartment
          ? {
              connect: data.apartment,
            }
          : undefined,

        check: data.check
          ? {
              connect: data.check,
            }
          : undefined,
      },
      select: {
        apartment: {
          select: {
            id: true,
          },
        },

        check: {
          select: {
            id: true,
          },
        },

        clientEmail: true,
        createdAt: true,
        endReservation: true,
        id: true,
        startReservation: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Reservation] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ReservationFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Reservation[]> {
    const args = plainToClass(ReservationFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        apartment: {
          select: {
            id: true,
          },
        },

        check: {
          select: {
            id: true,
          },
        },

        clientEmail: true,
        createdAt: true,
        endReservation: true,
        id: true,
        startReservation: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Reservation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ReservationWhereUniqueInput
  ): Promise<Reservation | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        apartment: {
          select: {
            id: true,
          },
        },

        check: {
          select: {
            id: true,
          },
        },

        clientEmail: true,
        createdAt: true,
        endReservation: true,
        id: true,
        startReservation: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Reservation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ReservationWhereUniqueInput,
    @common.Body() data: ReservationUpdateInput
  ): Promise<Reservation | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          apartment: data.apartment
            ? {
                connect: data.apartment,
              }
            : undefined,

          check: data.check
            ? {
                connect: data.check,
              }
            : undefined,
        },
        select: {
          apartment: {
            select: {
              id: true,
            },
          },

          check: {
            select: {
              id: true,
            },
          },

          clientEmail: true,
          createdAt: true,
          endReservation: true,
          id: true,
          startReservation: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Reservation",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Reservation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ReservationWhereUniqueInput
  ): Promise<Reservation | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          apartment: {
            select: {
              id: true,
            },
          },

          check: {
            select: {
              id: true,
            },
          },

          clientEmail: true,
          createdAt: true,
          endReservation: true,
          id: true,
          startReservation: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
