/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteNestoArgs } from "./DeleteNestoArgs";
import { NestoFindManyArgs } from "./NestoFindManyArgs";
import { NestoFindUniqueArgs } from "./NestoFindUniqueArgs";
import { Nesto } from "./Nesto";
import { NestoService } from "../nesto.service";

@graphql.Resolver(() => Nesto)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class NestoResolverBase {
  constructor(
    protected readonly service: NestoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Nesto",
    action: "read",
    possession: "any",
  })
  async _nestosMeta(
    @graphql.Args() args: NestoFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Nesto])
  @nestAccessControl.UseRoles({
    resource: "Nesto",
    action: "read",
    possession: "any",
  })
  async nestos(@graphql.Args() args: NestoFindManyArgs): Promise<Nesto[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Nesto, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Nesto",
    action: "read",
    possession: "own",
  })
  async nesto(
    @graphql.Args() args: NestoFindUniqueArgs
  ): Promise<Nesto | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Nesto)
  @nestAccessControl.UseRoles({
    resource: "Nesto",
    action: "delete",
    possession: "any",
  })
  async deleteNesto(
    @graphql.Args() args: DeleteNestoArgs
  ): Promise<Nesto | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
