/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateOwnerArgs } from "./CreateOwnerArgs";
import { UpdateOwnerArgs } from "./UpdateOwnerArgs";
import { DeleteOwnerArgs } from "./DeleteOwnerArgs";
import { OwnerFindManyArgs } from "./OwnerFindManyArgs";
import { OwnerFindUniqueArgs } from "./OwnerFindUniqueArgs";
import { Owner } from "./Owner";
import { ApartmentFindManyArgs } from "../../apartment/base/ApartmentFindManyArgs";
import { Apartment } from "../../apartment/base/Apartment";
import { OwnerService } from "../owner.service";

@graphql.Resolver(() => Owner)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class OwnerResolverBase {
  constructor(
    protected readonly service: OwnerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Owner",
    action: "read",
    possession: "any",
  })
  async _ownersMeta(
    @graphql.Args() args: OwnerFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Owner])
  @nestAccessControl.UseRoles({
    resource: "Owner",
    action: "read",
    possession: "any",
  })
  async owners(@graphql.Args() args: OwnerFindManyArgs): Promise<Owner[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Owner, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Owner",
    action: "read",
    possession: "own",
  })
  async owner(
    @graphql.Args() args: OwnerFindUniqueArgs
  ): Promise<Owner | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Owner)
  @nestAccessControl.UseRoles({
    resource: "Owner",
    action: "create",
    possession: "any",
  })
  async createOwner(@graphql.Args() args: CreateOwnerArgs): Promise<Owner> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Owner)
  @nestAccessControl.UseRoles({
    resource: "Owner",
    action: "update",
    possession: "any",
  })
  async updateOwner(
    @graphql.Args() args: UpdateOwnerArgs
  ): Promise<Owner | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Owner)
  @nestAccessControl.UseRoles({
    resource: "Owner",
    action: "delete",
    possession: "any",
  })
  async deleteOwner(
    @graphql.Args() args: DeleteOwnerArgs
  ): Promise<Owner | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Apartment])
  @nestAccessControl.UseRoles({
    resource: "Apartment",
    action: "read",
    possession: "any",
  })
  async apartments(
    @graphql.Parent() parent: Owner,
    @graphql.Args() args: ApartmentFindManyArgs
  ): Promise<Apartment[]> {
    const results = await this.service.findApartments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
